application:
  name: simple-example
  project: testing-seitosan
  cloud_region: aws/eu-west-3
  publicly_accessible: true
databases:
- type: mysql
  version: "5.7"
  name: my-mysql-3498225
routers:
- name: main
  routes:
  - application_name: simple-example
    paths:
    - /*
